#!/usr/bin/env python3
"""Generate exact-rational nine-point Route-B derivative weights.

The generated table contains direct D1, D2, D3, and D4 formulas at every
possible evaluation position in a nine-point uniform window.  It deliberately
does not construct higher derivatives by multiplying a first-derivative
matrix.  Python Fraction Gaussian elimination is the offline exact oracle.
"""

from __future__ import annotations

import argparse
import hashlib
import math
from fractions import Fraction
from pathlib import Path


WINDOW = 9
DERIVATIVES = range(1, 5)


def solve_fraction_system(matrix: list[list[Fraction]], rhs: list[Fraction]) -> list[Fraction]:
    size = len(rhs)
    augmented = [row[:] + [rhs[i]] for i, row in enumerate(matrix)]
    for column in range(size):
        pivot = next(row for row in range(column, size) if augmented[row][column])
        augmented[column], augmented[pivot] = augmented[pivot], augmented[column]
        scale = augmented[column][column]
        augmented[column] = [entry / scale for entry in augmented[column]]
        for row in range(size):
            if row == column:
                continue
            factor = augmented[row][column]
            if factor:
                augmented[row] = [
                    augmented[row][j] - factor * augmented[column][j]
                    for j in range(size + 1)
                ]
    return [augmented[row][-1] for row in range(size)]


def exact_weights(derivative: int, evaluation_position: int) -> list[Fraction]:
    offsets = [Fraction(column - evaluation_position) for column in range(WINDOW)]
    matrix = [[offset**power for offset in offsets] for power in range(WINDOW)]
    rhs = [Fraction(math.factorial(derivative) if power == derivative else 0)
           for power in range(WINDOW)]
    return solve_fraction_system(matrix, rhs)


def all_weights() -> list[list[list[Fraction]]]:
    return [[exact_weights(derivative, row) for row in range(WINDOW)]
            for derivative in DERIVATIVES]


def canonical_table(weights: list[list[list[Fraction]]]) -> str:
    lines = []
    for derivative, table in zip(DERIVATIVES, weights):
        for row, entries in enumerate(table):
            lines.append(
                f"D{derivative}/row{row}:" +
                ",".join(f"{entry.numerator}/{entry.denominator}" for entry in entries)
            )
    return "\n".join(lines) + "\n"


def cpp_number(value: Fraction) -> str:
    if value.denominator == 1:
        return f"{value.numerator}.0"
    return f"{value.numerator}.0 / {value.denominator}.0"


def render() -> str:
    weights = all_weights()
    checksum = hashlib.sha256(canonical_table(weights).encode()).hexdigest()
    l1 = [[sum(abs(float(value)) for value in row) for row in table]
          for table in weights]
    l2 = [[math.sqrt(sum(float(value) ** 2 for value in row)) for row in table]
          for table in weights]
    lines = [
        "#pragma once",
        "",
        "#include <Kokkos_Core.hpp>",
        "",
        "#include <cstddef>",
        "",
        "namespace teuk {",
        "",
        "// Generated by tools/numerical/generate_routeb_fornberg_weights.py.",
        "// Do not hand edit. Entries are exact rational uniform-grid weights",
        "// emitted as binary64 divisions; spacing powers are applied at use.",
        f'inline constexpr const char* routeb_fornberg_weights_sha256 = "{checksum}";',
        "inline constexpr std::size_t routeb_fornberg_window = 9;",
        "inline constexpr std::size_t routeb_fornberg_derivative_count = 4;",
        "KOKKOS_INLINE_FUNCTION constexpr double routeb_fornberg_weight(",
        "    const std::size_t derivative_index, const std::size_t row,",
        "    const std::size_t column) {",
        "  const std::size_t flat =",
        "      (derivative_index * routeb_fornberg_window + row) *",
        "          routeb_fornberg_window +",
        "      column;",
        "  switch (flat) {",
    ]
    for derivative_index, table in enumerate(weights):
        for row_index, row in enumerate(table):
            for column, value in enumerate(row):
                flat = ((derivative_index * WINDOW + row_index) * WINDOW +
                        column)
                lines.append(f"    case {flat}: return {cpp_number(value)};")
    lines.extend([
        "    default: return 0.0;",
        "  }",
        "}",
        "inline constexpr Kokkos::Array<double, routeb_fornberg_derivative_count>",
        "    routeb_fornberg_maximum_l1_norm{{" +
        ", ".join(f"{max(norms):.17e}" for norms in l1) + "}};",
        "inline constexpr Kokkos::Array<double, routeb_fornberg_derivative_count>",
        "    routeb_fornberg_maximum_l2_norm{{" +
        ", ".join(f"{max(norms):.17e}" for norms in l2) + "}};",
        "",
        "}  // namespace teuk",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    expected = render()
    if arguments.check:
        actual = arguments.output.read_text()
        if actual != expected:
            raise SystemExit(f"stale Route-B Fornberg weights: {arguments.output}")
        print("Route-B Fornberg generated-weight freshness: PASS")
        return
    arguments.output.write_text(expected)
    print(arguments.output)


if __name__ == "__main__":
    main()
