#!/usr/bin/env python3
"""Generate exact constrained spin +2 scri coefficient-extraction weights."""

from __future__ import annotations

import argparse
from fractions import Fraction
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "include/teuk/plus2_endpoint_extraction_weights.hpp"


def solve(nodes: list[int], extracted_power: int) -> list[Fraction]:
    # Exact Gauss-Jordan solve of sum_j w_j j^k = delta(k,p).
    n = len(nodes)
    a = [
        [Fraction(node) ** power for node in nodes]
        + [Fraction(int(power == extracted_power))]
        for power in range(n)
    ]
    for column in range(n):
        pivot = next(row for row in range(column, n) if a[row][column])
        a[column], a[pivot] = a[pivot], a[column]
        scale = a[column][column]
        a[column] = [value / scale for value in a[column]]
        for row in range(n):
            if row == column:
                continue
            scale = a[row][column]
            a[row] = [left - scale * right for left, right in zip(a[row], a[column])]
    return [a[row][-1] for row in range(n)]


def fraction_literal(value: Fraction) -> str:
    return f"{value.numerator}.0 / {value.denominator}.0"


def render() -> str:
    q0 = solve(list(range(1, 7)), 2)
    q1 = solve(list(range(1, 6)), 1)
    assert q0 == [Fraction(29, 6), Fraction(-461, 24), Fraction(31),
                  Fraction(-307, 12), Fraction(65, 6), Fraction(-15, 8)]
    assert q1 == [Fraction(-77, 12), Fraction(107, 6), Fraction(-39, 2),
                  Fraction(61, 6), Fraction(-25, 12)]
    l1_q0 = sum(map(abs, q0))
    l2_q0 = sum(value * value for value in q0)
    l1_q1 = sum(map(abs, q1))
    l2_q1 = sum(value * value for value in q1)
    rows = lambda values: ",\n    ".join(fraction_literal(v) for v in values)
    return f'''#pragma once

#include <Kokkos_Core.hpp>

#include <cstddef>

namespace teuk {{

// Generated by tools/numerical/generate_plus2_endpoint_extraction.py.
// Nodes are the six/five strictly positive points R=j h.  The q0 moments
// annihilate powers 0,1,3,4,5 and extract the R^2 coefficient; the q1 moments
// annihilate powers 0,2,3,4 and extract the R coefficient.  Therefore neither
// stencil uses or overwrites the separately measured R=0 peeling residuals.
inline constexpr std::size_t plus2_q0_endpoint_nodes = 6;
inline constexpr std::size_t plus2_q1_endpoint_nodes = 5;
inline constexpr Kokkos::Array<double, plus2_q0_endpoint_nodes>
    plus2_q0_endpoint_weights{{{{
    {rows(q0)}}}}};
inline constexpr Kokkos::Array<double, plus2_q1_endpoint_nodes>
    plus2_q1_endpoint_weights{{{{
    {rows(q1)}}}}};

inline constexpr double plus2_q0_endpoint_l1 = {fraction_literal(l1_q0)};
inline constexpr double plus2_q0_endpoint_l2_squared =
    {fraction_literal(l2_q0)};
inline constexpr double plus2_q0_endpoint_linf = 31.0;
inline constexpr double plus2_q1_endpoint_l1 = {fraction_literal(l1_q1)};
inline constexpr double plus2_q1_endpoint_l2_squared =
    {fraction_literal(l2_q1)};
inline constexpr double plus2_q1_endpoint_linf = 39.0 / 2.0;

}}  // namespace teuk
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = render()
    if args.check:
        return 0 if OUTPUT.exists() and OUTPUT.read_text() == generated else 1
    OUTPUT.write_text(generated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
